version: "3.8"
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - type: bind
        source: .
        target: /go/src/app
      - type: volume
        source: go_modules
        target: /go/pkg/mod
    tty: true
    command: "air -c .air.toml"
volumes:
  go_modules:
